### ISSUE TITLE
Latest react-styleguidist only works with a very narrow dependency on react-docgen

### ISSUE THREAD

**Issue by matthew-dean** [styleguidist/react-styleguidist#1177]
**Current behavior**

Since updating Styleguidist to the latest version, I've been getting these errors:

```
Warning: Cannot parse src/common/presentation/elements/Anchor/Anchor.js: RangeError: Maximum call stack size exceeded

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues

Warning: Cannot parse src/common/presentation/elements/Avatar/Avatar.js: RangeError: Maximum call stack size exceeded

It usually means that react-docgen does not understand your source code, try to file an issue here:
https://github.com/reactjs/react-docgen/issues
```
I found that if I tried a different react-docgen dependency, (Beta 6 AND RC 1), they both fail.

**To reproduce**

Run `npm install react-docgen@3.0.0-rc.1`. Try to build the Styleguide

**Expected behavior**

Styleguidist should work with newer versions of react-docgen other than just the narrow matching version of beta 12.

Related issue on react-docgen: https://github.com/reactjs/react-docgen/issues/303

**Comment by matthew-dean** [comment]
Confirmed (by installing different versions of Styleguidist) that Styleguidist started failing with versions of react-docgen other than beta12 at react-styleguidist version 7.1. 7.0 does not have this issue.

**Comment by sapegin** [comment]
Not sure we can do anything on our side ;-/

**Comment by matthew-dean** [comment]
@sapegin Well, maybe. But Styleguidist 7.0 didn't have this issue. So, yes, it may be a `react-docgen` bug, but 7.0 didn't trigger it, or Styleguidist is calling something in `react-docgen` which is causing an error, but only for those other versions. So that could be something to look at; what changed after 7.0. Because, considering `react-docgen` is on RC1, it's likely that this will continue to be an issue and Styleguidist may never be able to upgrade without addressing or circumventing the issue as it did before 7.1.

**Comment by danez** [comment]
Can anyone share an example of a file which fails? I tried reproducing this error in react-docgen, but so far had no luck.

**Comment by danez** [comment]
We released react-docgen@3.0.0-rc.2, it has the latest version of recast and babel and some fixes. Let me know if that makes it any better.

**Comment by macintoshhelper** [comment]
@danez Hi, thanks! `react-docgen@3.0.0-rc.2` fixes the issue for me, have opened a PR to update to it.

**Comment by reintroducing** [comment]
this actually caused my SG to stop working when I upgraded to v8.0.5 (v8.0.4 works perfectly fine). This is what I started to see with v8.0.5:
```
Cannot find module 'react-docgen/dist/babylon'
npx styleguidist server --open exited with code 1
```

**Comment by reintroducing** [comment]
I am not, but this is: https://github.com/siddharthkp/react-docgen-external-proptypes-handler/issues/5

Good callout, thanks.

**Comment by arizonatribe** [comment]
I ran into this tonight as well. I'm using `react-styleguidist` version 8.0.6 in a multi-package repo. One of the adjacent packages has a custom build script that uses and installs `react-docgen` directly, but an older version (2.2.1), so I tried to upgrade the version it's requiring.

Even though `react-styleguidist` is asking for that 3.0.0-rc.2 (and I confirmed it's installed in the `node_modules/react-styleguidist/node_modules/react-docgen` directory) it seems it's falling through to the one at the root of the repo (which is version 2.2.1). Before following the advice on this thread I noticed that `react-docgen` published version 3.0.0 several days ago, so I tried that one, but the error still persisted.

However when I rolled it back down to the 3.0.0-rc.2 it worked 🎊 , just as advised on this thread. So, it seems to me that the newly published version 3.0.0 of `react-docgen` is a regression, and I've since locked us in at version 3.0.0-rc.2 to fix the problem. I know it's a `react-docgen` issue, but just a heads-up.

I've run into an issue like this before where our build tools were installing version 5 of ESLint, but whenever installed into an app that asked for version 4 of ESLint, it caused our tool to use that version instead of the one we know works with our tool. To solve it I made a function that loops through several possible paths and wraps `require.resolve` in `try` / `catch` that continues looping until it resolves a path or runs out of paths to try (ie, look for the nearby ESlint `require.resolve(path.resolve(__dirname, '../node_modules/eslint'))` before falling back to a `require.resolve('eslint')`).

Just a thought to try, in case you see more issues open/re-opened for problems with external dependencies.

Thanks
